### ISSUE TITLE
Naming of freeSurfer parcellations

### ISSUE THREAD

**Issue by ansk** [BIDS-Apps/MRtrix3_connectome#10]
I have noticed that both Desikan and Destrieux parcellations files are not correctly referenced.
The Desikan parcellation file is aparc+aseg.mgz
The Destrieux parcellation file is aparc.a2009s+aseg.mgz

**Comment by Lestropie** [comment]
Hi @ansk,

When you say 'not correctly referenced', do you mean that the script constructs the path to those files incorrectly (i.e. [here](https://github.com/BIDS-Apps/MRtrix3_connectome/blob/master/run.py#L255-L258), and therefore the script fails as the subsequent [labelconvert call](https://github.com/BIDS-Apps/MRtrix3_connectome/blob/master/run.py#L261) fails to find the image file?

I have a vague recollection of having noticed something odd at this point when first writing the script; I wonder if the names of those files changed between the regular FreeSurfer 5.3.0 release and the 'HCP' release. Looks like I [reverted to the non-HCP version](https://github.com/BIDS-Apps/MRtrix3_connectome/commit/9e693eb3c3dcbbce11359641c5ad56ef8d2f2690#diff-3254677a7917c6c01f55212f86c57fbfR17) in the Docker container; that may be where the problem has come from. (I can't test the FreeSurfer parcellation in the CircleCI tests as they take too long to generate)

We're currently polishing off the next [*MRtrix3* update](https://github.com/MRtrix3/mrtrix3/pull/785); once that's done I'll hopefully come back to this project, bring it up to date / do some more testing / add a little spit-and-polish. I'll make sure this gets looked at as part of that process.

Thanks for the report!
Rob
