### ISSUE TITLE
Updates for MRtrix3 3.0_RC2

### ISSUE THREAD

**Issue by Lestropie** [BIDS-Apps/MRtrix3_connectome#13]
- Modify dockerfile to pull the `3.0_RC2` tag.

- Use `mrdegibbs` rather than `unring.a64`.

- Use `mtnormalise`, including accounting for the scaling factor embedded in the image header in group-level analysis. Remove `dwiintensitynorm` step.

- Consider incorporating upsampling of DWI data (if >= 2.0mm) prior to CSD.

**Comment by Lestropie** [comment]
Additionally: Incorporate changes relating to command-line interface in 45fbb8f (requires *MRtrix3* commit 09c1f21).

@chrisfilo: With the above, I'll have full control over what command-line options are available only when the script is run within a container. Previously we standardised `--participant_label`, `--n_cpus` and `-v/--version` for BIDS Apps; I'm also retaining `-d/--debug` from the *MRtrix3* library, since it produces *much* more terminal output and makes it a lot easier for me to see what's going wrong if anyone reports an error. Are there any additional command-line options that you are hoping to see standardised for OpenNeuro?

**Comment by chrisfilo** [comment]
Great. Whenever you release a new version we'll deploy it on OpenNeuro.

**Comment by Lestropie** [comment]
Closing since the latest version is based on *MRtrix3* version `3.0_RC3`. Some elements listed here will go into a new issue instead.
