### ISSUE TITLE
First working version of app

### ISSUE THREAD

**Issue by Lestropie** [BIDS-Apps/MRtrix3_connectome#2]
Adding some details so that @chrisfilo (and anybody else who stumbles across this) can see what is required to get a baseline version of the app running. List may be altered as I test & adjust minimal requirements.

* Finish *MRtrix3* developments that will enable DWI pre-processing to be run without _a priori_ knowledge of the phase-encoding design of either DWI or EPI SE field-mapping protocols, by reading this information from the image headers when available and passing this information to FSL's `topup` / `eddy` accordingly.

* Testing of both participant and group-level analyses (which will involve inter-subject connection density normalisation followed by calculation of the group average connectome).

**Comment by Lestropie** [comment]
Update: DWI pre-processing is working. Currently participant level analysis makes it to parcellation: CircleCI times out on `recon-all` after 2 hours, and FreeSurfer seems to be hanging indefinitely when run on my local container (need to dig deeper here). Have changed the CircleCI test to use the AAL parcellation. Initial 'version' of App (at least that is present when the BIDS Apps manuscript is submitted) will likely have the group level analysis disabled; but the bulk of the content in this analysis is yet unpublished anyways.

**Comment by chrisfilo** [comment]
Good news! I would keep CircleCI minimalistic. For Freesurfer app I only
run autorecon1 - just to check if it will not break.

**Comment by Lestropie** [comment]
@chrisfilo 

[The box is green](https://circleci.com/gh/BIDS-Apps/MRtrix3_connectome/36). :-D

Group level testing is disabled because I'm still tinkering, but it's actually not too far away, and the app can very much be used without group-level analysis.

Rob
