### ISSUE TITLE
Add --skip-bids-validator option

### ISSUE THREAD

**Issue by Lestropie** [BIDS-Apps/MRtrix3_connectome#21]
As discussed [here](https://github.com/BIDS-Apps/example/issues/19).

**Comment by jlhanson5** [comment]
Is this available in the latest docker version? I tried it with the following syntax:

`docker run -i --rm -v ~/Volumes/Hanson/NKI_HealthyBrainNetwork/RU/R1/:/bids_dataset -v /home/jamielh/Volumes/Hanson/NKI_HealthyBrainNetwork/RU/R1/derivatives/MRtrix3:/outputs bids/mrtrix3_connectome /bids_dataset /outputs participant --participant_label NDARAG340ERT --skip-bids-validator --parcellation fs_2005 -nocleanup -n 5 `

But get the following error
`Error: unrecognized arguments: --skip-bids-validator
Usage: run.py bids_dir output_dir analysis_level [ options ]
       (Run run.py -help for more information)`

Am I entering the flag wrong (if it is available)?

**Comment by Lestropie** [comment]
No, I've not gotten around to implementing it yet; I had a fellowship application due yesterday :-/

One little trick: If you execute the container but do not provide any command-line arguments (i.e. just: "`docker run -it --rm bids/mrtrix3_connectome`"), you should get a help page describing exactly which command-line options are available for the particular version installed. This is a functionality that's common with the Python scripts in *MRtrix3* as I make use of the same libraries.
