### ISSUE TITLE
bids-validator failure.

### ISSUE THREAD

**Issue by jlhanson5** [BIDS-Apps/MRtrix3_connectome#22]
Hello MRtrix3_connectome user, 

I was trying to test drive this bids app, but ran into some slightly "opaque" errors.  When trying to use this syntax:
`docker run -i --rm -v ~/Volumes/Hanson/NKI_HealthyBrainNetwork/RU/R1/:/bids_dataset -v /home/jamielh/Volumes/Hanson/NKI_HealthyBrainNetwork/RU/R1/derivatives/MRtrix3:/outputs bids/mrtrix3_connectome /bids_dataset /outputs participant --participant_label NDARAG340ERT --parcellation fs_2005 -nocleanup -n 5`

I get the following output:
`Command:  bids-validator /bids_dataset
run.py:
run.py: [ERROR] Command failed: bids-validator /bids_dataset (run.py:659)
run.py: Output of failed command:

        <--- Last few GCs --->

          944598 ms: Scavenge 1398.9 (1457.1) -> 1398.9 (1457.1) MB, 1.7 / 0 ms (+ 1.6 ms in 1 steps since last GC) [allocation failure] [incremental marking delaying mark-sweep].
          945879 ms: Mark-sweep 1398.9 (1457.1) -> 1397.8 (1457.1) MB, 1280.6 / 0 ms (+ 1.6 ms in 1 steps since start of marking, biggest step 1.6 ms) [last resort gc].
          947042 ms: Mark-sweep 1397.8 (1457.1) -> 1398.4 (1457.1) MB, 1163.4 / 0 ms [last resort gc].

        <--- JS stacktrace --->

        ==== JS stack trace =========================================

        Security context: 0x5df37337399 <JS Object>
            2: /* anonymous */ [/usr/lib/node_modules/bids-validator/validators/bids.js:209] [pc=0x19fa99d4d554] (this=0x5df373b8139 <JS Global Object>,file=0x25df25b6cbf1 <an Object with map 0x1d7a42fde8f1>,key=0x2ad7a5531141 <String[7]: 1188769>,cb=0x180a2edc0901 <JS Function (SharedFunctionInfo 0x2ad7a55552d1)>)
            3: iterateeCallback(aka iterateeCallback) [/usr/lib/node_modules/bids-validator/node_...

        FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
run.py:`

My bids directory has a fair number of subjects (271), each with multiple types of scans (structural, rest, DTI)... so I wasn't sure if this was causing an issue... or if there was something in my call that hung things up? Has anyone run into this? Any thoughts are greatly appreciated!

Thanks much!
Jamie.

**Comment by Lestropie** [comment]
That's the first time I've seen anything like that. My guess is that there's some obscure issue with your BIDS dataset that's causing the validator to stumble rather than properly identify and report the error. I can't really help here over and above alerting @chrisfilo.

**Comment by jlhanson5** [comment]
I think you were pretty dead on... There's something wacky in one of my json files and/or the high # of files needed to validate screwed something up. I copied one subject into a test directory and things executed fine (and are currently running). Thanks!
