### ISSUE TITLE
docker documentation inconsistent: output vs outputs

### ISSUE THREAD

**Issue by dkp** [BIDS-Apps/MRtrix3_connectome#34]
https://github.com/BIDS-Apps/MRtrix3_connectome

To run the script in participant level mode (for processing one subject only), use e.g.:

$ docker run -i --rm \
      -v /Users/yourname/data:/bids_dataset \
      -v /Users/yourname/outputs:/outputs \
      bids/mrtrix3_connectome \
      /bids_dataset **/outputs** participant --participant_label 01 --parcellation desikan
Following processing of all participants, the script can be run in group analysis mode using e.g.:

$ docker run -i --rm \
      -v /Users/yourname/data:/bids_dataset \
      -v /Users/yourname/output:**/output** \
      bids/mrtrix3_connectome \
      /bids_dataset /output group

**Comment by Lestropie** [comment]
Thanks for the spot; this will get revised by 0b121e63 when I finalise the next update and commit a new tag.
