### ISSUE TITLE
Name of T1w image too restrictive

### ISSUE THREAD

**Issue by dkp** [BIDS-Apps/MRtrix3_connectome#39]
Hi, 
sub-01_T1w.nii is okay, but the run exits prematurely if the image is named sub-01_acq-mprage_T1w.nii (I think I got this right)...the point is, there are other acceptable names for this file from the BIDS validator point of view, but MRtrix3_connectome doesn't seem to handle these. Thanks for working so hard to provide this interesting tool.

**Comment by Lestropie** [comment]
Yes, I found that one myself recently; it's fixed in 94a71f89 and 27dc8b6b, I just need to settle on what I am and am not including in the tag update and then push it though.
