### ISSUE TITLE
Fail when using hcpmmp1 atlas and verbosity level 3

### ISSUE THREAD

**Issue by dkp** [BIDS-Apps/MRtrix3_connectome#47]
Here is the command I ran (I have previously run this command successfully with the desikan atlas and no output verbosity flag):

dpat@Saci:/Volumes/Main/working/MRtrix_connectome2/data% docker run -i --rm -v ${PWD}:/bids_dataset -v ${PWD}/derivatives:/outputs diannepat/mrtrix3-hotfix /bids_dataset /outputs participant --participant_label 102 --parcellation hcpmmp1 --output_verbosity 3 --debug --skip-bids-validator

The error.txt contents:
labelconvert freesurfer/mri/aparc.HCPMMP1+aseg.mgz/aparc.HCPMMP1+aseg.mgz /mrtrix3/share/mrtrix3/labelconvert/hcpmmp1_original.txt /mrtrix3/share/mrtrix3/labelconvert/hcpmmp1_ordered.txt parc_init.mif

labelconvert: [00;32m[INFO] opening image "freesurfer/mri/aparc.HCPMMP1+aseg.mgz/aparc.HCPMMP1+aseg.mgz"...[0m
labelconvert: [01;31m[ERROR] Not a directory[0m
labelconvert: [01;31m[ERROR] error opening image "freesurfer/mri/aparc.HCPMMP1+aseg.mgz/aparc.HCPMMP1+aseg.mgz"[0m

I have saved the entire results directory, so if there is anything else you need, please let me know.  I just started rerunning with the desikan atlas to see if it completes (since this *looks* like the issue from the error.txt).

Thank you,

Dianne

**Comment by Lestropie** [comment]
Thanks for the report. Looks like I've buggered up and erroneously duplicated a line of code in the process of resolving different branches of code. The fix should be as simple as d69df96, but I'll hopefully leave a system running through the script overnight with your settings to confirm.

Ideally I'd test every possible set of command-line options as part of Continuous Integration, but unfortunately the run-times are too long :-(

**Comment by Lestropie** [comment]
Closed by #43, should now be on Docker Hub as 0.4.2.

**Comment by dkp** [comment]
Thank you so much!  I look forward to trying it.
