### ISSUE TITLE
mrconvert parcRGB.mif ... Error when using parcellation=perry512

### ISSUE THREAD

**Issue by paul-triebkorn** [BIDS-Apps/MRtrix3_connectome#57]
Hi developers
Thanks for the nice container. 

I just encountered a minor issue. 
When running the container with --parcellation perry512 and --output_verbosity 3,
the container generates an error at the last steps.

mrtrix3_connectome.py: [ERROR] Command failed: mrconvert parcRGB.mif /mrtrix3_out/sub-QL20120814/anat/sub-QL20120814_parc-perry512_colour.nii.gz -strides +1,+2,+3 (mrtrix3_connectome.py:797)
mrtrix3_connectome.py: Output of failed command:
                       mrconvert: [INFO] opening image "parcRGB.mif"...
                       mrconvert: [ERROR] failed to open key/value file "parcRGB.mif": No such file or directory
                       mrconvert: [ERROR] error opening image "parcRGB.mif"

I assume this is because "parcRGB.mif" is not created on line 650 in mrtrix3_connectome.py, 
cause mrtrix_lut_file is empty for the specified parcellation. 
However on line 797 mrconvert tries to use that ".mif" file and thus generates the Error. 

best
Paul

**Comment by Lestropie** [comment]
Hi Paul,

Good catch. Suppose this sort of thing is why many softwares rely on comprehensive CI testing matrices to stress-test all possible combinations of parameters...

I've not been able to put the time into this tool I'd like to, with the *MRtrix3* workshop last week and now trying to get that software released; but I'll try to put a fix for this together with some of the other changes I've been making and push a new version.

Rob
