### ISSUE TITLE
Some typos in parc-hcpmmp1_lookup.txt ?

### ISSUE THREAD

**Issue by paul-triebkorn** [BIDS-Apps/MRtrix3_connectome#58]
Hi 

I think I found some typos within hcpmmp1_ordered.txt/hcpmmp1_original.txt/parc-hcpmmp1_lookup.txt

All "L" or "l" of right hemisphere regions seem to be converted to "R".
I encountered this mistake when I tried to map the connectome region names to the names in the annotation file from freesurfer. 
Comparing with the names in Glasser et al. 2016 I found the following typos.

ID false correct
20 RO1 LO1
21 RO2 LO2
25 PSR PSL
26 SFR SFL
39 5R  5L
42 7AR 7AL
46 7PR 7PL
48 RIPv LIPv
70 8BR  8BL
76 47R 47l
91 11R 11l
92 13R 13l
95 RIPd LIPd
124 PBeRt PBelt
159 RO3 LO3
173 MBeRt MBelt
174 RBeRt LBelt

best
Paul

**Comment by Lestropie** [comment]
Hi Paul,

Thanks for the report.

These files are a part of the https://github.com/MRtrix3/mrtrix3 repository, so I have to make the changes over there, and then bring the upstream fix in to this tool. If possible could you please verify MRtrix3/mrtrix3#1722? The indices you gave were for the left hemisphere nodes whereas the name changes were for the right hemisphere, so I want to be absolutely sure that the change is correct.

Thanks
Rob

**Comment by paul-triebkorn** [comment]
Hi Rob, 

The new file is almost correct. 
Just change 
354  R_RBelt
to 
354  R_LBelt

That should be it. 

Now also my mapping to the freesurfer annotation file works. 

best
Paul
