### ISSUE TITLE
Test data - fmap data

### ISSUE THREAD

**Issue by Lestropie** [BIDS-Apps/MRtrix3_connectome#6]
Need a test data set that includes reversed phase-encode EPI data for susceptibility distortion correction. From memory I went through the BIDS example data list and didn't find anything. @chrisfilo Are you able to add something, or is there a way for me to upload a couple of data sets?

**Comment by Lestropie** [comment]
I'll have to ask the boss about permissions seeing as though the data would be publicly accessible. Hopefully we'll figure something out.

**Comment by chrisfilo** [comment]
One subject (you might even considering downsampling) should suffice.

**Comment by Lestropie** [comment]
Test data are currently hosted from my own Dropbox. Consists of two subjects (which means that the group-wise step can also be tested), for which pre-processing has already been performed (and the relevant steps of the script are therefore skipped using the `-preprocessed` option), and the images have then been down-sampled.
