### ISSUE TITLE
Getting eddy_options

### ISSUE THREAD

**Issue by araikes** [BIDS-Apps/MRtrix3_connectome#60]
Related to #59, the script is not grabbing the eddy_options correctly. Here's the command (in the current release posted):

```
eddy_help_process = subprocess.Popen([ eddy_binary, '--help' ], stdin=None, stdout=subprocess.PIPE, stderr=subprocess.PIPE, shell=False)
(eddy_stdout, eddy_stderr) = eddy_help_process.communicate()
app.var(eddy_stdout, eddy_stderr)
eddy_options = []
for line in eddy_stderr:
      line = line.lstrip()
      if line.startswith('--repol'):
        eddy_options.append('--repol')
      elif line.startswith('--mporder') and have_slice_timing and eddy_cuda:
        eddy_options.append('--mporder=' + str(mporder))
```
As it stands, it is grabbing each character as `line`, so it isn't actually grabbing any options. For example, since FSL 6.0.0 is installed in the current version, `--repol` should always be present but isn't getting propagated into the call. I have this working for updated python  (v 3.6.8) inside the container.

```
for line in eddy_stderr.strip().split():
    line = line.decode('utf-8')
    if "--cnr_maps" in line :
        eddy_options.append('--cnr_maps')
    elif line.startswith('--repol'):
        eddy_options.append('--repol')
    elif line.startswith(
            '--mporder') and have_slice_timing and eddy_cuda:
        eddy_options.append('--mporder=' + str(mporder))
```

**Comment by Lestropie** [comment]
Yes, it should be looping over the output of `splitlines()`. Strange that that would make it in. Looks like I'll have to put together a 0.4.3...

**Comment by Lestropie** [comment]
Seems I already had this one fixed in my local working version, just never got around to committing the fix :disappointed:
