### ISSUE TITLE
minor typo in documentation (participant1 instead of participant)

### ISSUE THREAD

**Issue by dkp** [BIDS-Apps/MRtrix3_connectome#89]
To run the script in participant1 level mode (for processing one subject only), use e.g.:

$ docker run -i --rm \
      -v /Users/yourname/data:/bids_dataset \
      -v /Users/yourname/output:/output \
      bids/mrtrix3_connectome \
      /bids_dataset /output participant1 --participant_label 01 --parcellation desikan

**Comment by Lestropie** [comment]
Yes, I'd noted already that the README wasn't fully up to date with `0.5.0` changes. Earlier the "`preproc`" and "`participant`" analysis levels were called "`participant1`" and "`participant2`", hence the error. I'll try to expand on the instructions a little bit more.

**Comment by Lestropie** [comment]
Closed by 2f4f793a.
